- name: variables from vars_files
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration {{ DURATION }}, Trainer {{ TRAINER }}"